# В этой версии данный файл необходимо заполнить вручную
#
#  Telegram ID отслеживаемого пользователя (ID указывать в "")
#  "1234567890":
#    # Тип пользователя - позволяет создавать шаблоны заголовков в сообщениях
#    TYPE: Cyborg
#    # Список Telegram Chat ID в которых будет отслеживаться активность пользователя (ID указывать в "")
#    CHAT_IDS:
#      - "-1001234567890"
#      - "-1002345678901"
#    # Время отсутствия активности (мин), по истечении которого выводится сообщение об угрозе
#    INACTIVITY_ALERT_DELAY: 60
#    # Время отсутствия активности (мин), после которого выводится сообщение об отсутствии угроз
#    # При установке значения 0 - сообщения об отсутствии угроз не выводятся
#    STAND_DOWN_DELAY: 0
#    UNIQUE_COMMAND_REACTION: True


"1234567890":
  type: type1
  chat_ids:
    - "-1001234567890"
  inactivity_alert_delay: 720
  stand_down_delay: 60
  unique_command_reactions: True
